appenders:
    stdout:
        kind: console
        force_tty: true
        encoder:
            pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
        filters:
            - kind: threshold
              level: info
root:
    level: info
    appenders:
        - stdout
